### ISSUE TITLE
Cannot download tensorflow@python due to wrong url

### ISSUE THREAD

**Issue by kyleung-dev** [hectorqin/sublime-devdocs#3]
The plugin fail to download doc for tensorflow@Python.
http://dl.devdocs.io/tensorflow~Python.tar.gz is not exists now and http://dl.devdocs.io/tensorflow~python.tar.gz is accessable.

Log: 
Selected tensorflow@Python
Uninstall languageWithVersion tensorflow@Python
Install languageWithVersion tensorflow@Python
Downloading http://dl.devdocs.io/tensorflow~Python.tar.gz
Download success
DevDocs offline.DevDocs offline: HTTP error 404 contacting API

**Comment by hectorqin** [comment]
The latest version has solved this problem
